before_script:
  - uname -a

smoke-ubuntu: # smoke build - just test that it compiles
  image: ubuntu
  script:
    - apt-get update -qq && apt-get install -y -qq git cmake g++ libfuse-dev libcurl4-gnutls-dev libjsoncpp-dev
    - git submodule update --init --recursive # update curlcpp and googletest
    - mkdir build
    - cd build
    - cmake ..
    - "make -j$(nproc)"
  artifacts:
    paths:
      - build/marcfs
  
