variables:
  GET_SOURCES_ATTEMPTS: "3"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_SSL_NO_VERIFY: "true"

stages:
  - ubuntu build
  - ubuntu fstest
  - mint build
  - mint fstest
  - fedora build
  - fedora fstest
  - arch build
  - arch fstest

build on ubuntu:
  image: ubuntu
  stage: ubuntu build
  dependencies: []
  before_script: &common_compile_debian
    - apt-get update -qq && apt-get install -y -qq git cmake g++ libfuse-dev libcurl4-gnutls-dev libjsoncpp-dev
  script: &common_script
    - mkdir build
    - cd build
    - cmake ..
    - "make -j$(nproc)"
    - ./apitest
  artifacts: &common_artifacts
    paths:
      - build/marcfs

fstest on ubuntu:
  image: ubuntu
  stage: ubuntu fstest
  dependencies:
    - build on ubuntu
  before_script: &common_test_debian
    - apt-get update -qq && apt-get install -y -qq fuse libcurl3-gnutls libjsoncpp1 python3
    - useradd --create-home fstest
    - cp build/marcfs tests/fstest.py ~fstest
    - "chown -R fstest: ~fstest"
  after_script: &common_fstest_after
    - userdel fstest
  script: &common_fstest_script
    - su -c 'python3 fstest.py -v' - fstest


build on mint:
  image: vcatechnology/linux-mint
  stage: mint build
  dependencies: []
  before_script: *common_compile_debian
  script: *common_script
  artifacts: *common_artifacts

fstest on mint:
  image: vcatechnology/linux-mint
  stage: mint fstest
  dependencies:
    - build on mint
  before_script: *common_test_debian
  after_script: *common_fstest_after
  script: *common_fstest_script

build on fedora:
  image: fedora
  stage: fedora build
  dependencies: []
  before_script: 
    - yum -y install git-all cmake gcc-c++ fuse-devel libcurl-devel jsoncpp-devel
  script: *common_script
  artifacts: *common_artifacts

fstest on fedora:
  image: fedora
  stage: fedora fstest
  dependencies:
    - build on fedora
  before_script:
    - yum -y install fuse libcurl jsoncpp python
    - useradd --create-home fstest
    - cp build/marcfs tests/fstest.py ~fstest
    - "chown -R fstest: ~fstest"
  after_script: *common_fstest_after
  script:
    - su -c 'export NSS_STRICT_NOFORK=DISABLED; python3 fstest.py -v' - fstest

  
build on arch:
# image: pritunl/archlinux # GPG signing errors
  image: base/archlinux
  stage: arch build
  dependencies: []
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm git make cmake gcc fuse2 libcurl-gnutls jsoncpp
  script: *common_script
  artifacts: *common_artifacts

fstest on arch:
# image: pritunl/archlinux
  image: base/archlinux
  stage: arch fstest
  dependencies:
    - build on arch
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm fuse2 libcurl-gnutls jsoncpp python
    - useradd --create-home fstest
    - cp build/marcfs tests/fstest.py ~fstest
    - "chown -R fstest: ~fstest"
  after_script: *common_fstest_after
  script: *common_fstest_script
